### ISSUE TITLE
Error when publishing to device

### ISSUE THREAD

**Issue by simengjermundsen** [distriqt/ANE-AndroidSupport#10]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Expected behaviour
Publishing completed

##### Actual behaviour
Publishing failed with:
Unknown error.
Warning: Using default implementation for native extension 'androidx.core'
ld: unexpected token: !tapi-tbd file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/usr/lib/libc++.tbd' for architecture arm64

##### Environment 

- AIR SDK version: AIR 33.0.2.315
- Device OS: iOS
- Device version: iOS 14.3
- Development IDE: Adobe Animate 
- Development OS: macOS Big Sur 11.2

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Please update to the latest version of AIR. This is related to the iOS linker.

**Comment by simengjermundsen** [comment]
Thank you! Worked!
