### ISSUE TITLE
Install Referrer not working

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-AndroidSupport#13]
Using the `com.android.installreferrer.ane`
This is the URL i'm getting
`referrerUrl=utm_source=(not%20set)&utm_medium=(not%20set) 
`
It doesn't include any information for some reason
any ideas?

**Comment by marchbold** [comment]
Those values are returned when the app is installed without a referrer parameter:

> For a deep link into Google Play where the referrer parameter is not present or empty, the referrer value provided is:
>
> `utm_source=(not%20set)&utm_medium=(not%20set)`


Are you using a link generate like the following: 

https://developers.google.com/analytics/devguides/collection/android/v4/campaigns#google-play-url-builder
