### ISSUE TITLE
Java11 Requires Kotlin Update

### ISSUE THREAD

**Issue by urthling** [distriqt/ANE-AndroidSupport#14]
Opening a ticket in anticipation of kotlin stdlib compatibility with Java 11

**Comment by marchbold** [comment]
We are looking into this one.

**Comment by marchbold** [comment]
Can you elaborate on the error you are seeing? We aren't seeing any errors related to this currently only some warnings that seem safe to ignore.

**Comment by urthling** [comment]
It will build but Dialogs won't work -- note what Andrew says about this and whyL
https://github.com/airsdk/Adobe-Runtime-Support/issues/1412#issuecomment-985260683

**Comment by marchbold** [comment]
Yes okay, but there is no error in that issue related to kotlin, just a warning which is safe to ignore. 

The issue with the dialogs you are seeing is most likely another issue with the java packaging, see:

- https://github.com/airsdk/Adobe-Runtime-Support/issues/1392
- https://github.com/airsdk/Adobe-Runtime-Support/issues/274#issuecomment-987949069

**Comment by urthling** [comment]
@marchbold this is not a warning:

`Unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: w: Runtime JAR files in the classpath have the version 1.4, which is older than the API version 1.5. Consider using the runtime of version 1.5, or pass '-api-version 1.4' explicitly to restrict the available APIs to the runtime of version 1.4. `

This is preventing the build from completing -- note `Unexpected failure`

So you're saying this build failure is to so with something else, other than this?

**Comment by marchbold** [comment]
Yeah, okay, that's nothing to do with kotlin.
