### ISSUE TITLE
AAB - Failed to parse XML resource file \androidx.appcompat\build\intermediates\packaged_res\release\values\values.xml

### ISSUE THREAD

**Issue by lwmirkk** [distriqt/ANE-AndroidSupport#16]
##### Expected behaviour
Generate AAB file or APK-DEBUG file
androidx.appcompat.ane required by com.distriqt.MediaPlayer.ane

##### Environment 

- AIR SDK version: 33.1.1.713
- Device OS: Android
- Device version: 
- Development IDE: Flash CC to generate SWF and command line to generate APK / AAB
- Development OS: Windows 10 21H2 (Java 11.0.12 x64)

##### ANEs
```
androidx.appcompat-1.2.0
androidx.core-1.3.2
androidx.vectordrawable-1.1.0
com.distriqt.Application-6.8.2
com.distriqt.Core-6.4.3
com.distriqt.Exceptions-3.0.8
com.distriqt.MediaPlayer-4.4.8
com.distriqt.PackageManager-3.1.025
com.distriqt.RestartApp-3.0.013
com.google.code.gson.gson-2.8.6
com.mesmotronic.ane.fullscreen-1.5.0
com.tuarua.frekotlin-1.42.0
WebViewANE-2.24.0
```

##### Logs

`NOTE: Multiple Android build-tools folders exist, choosing the latest version (31.0.0) for packaging
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':androidx.appcompat:parseReleaseLocalResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ParseLibraryResourcesTask$ParseResourcesRunnable
   > Failed to parse XML resource file 'C:\Users\XXX\AppData\Local\Temp\f8580962-92de-4c7e-a6ea-67211aa38ed2\androidx.appcompat\build\intermediates\packaged_res\release\values\values.xml'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

java.io.IOException: Unable to run java: com.adobe.air.ADTException: gradle tool failed:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':androidx.appcompat:parseReleaseLocalResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ParseLibraryResourcesTask$ParseResourcesRunnable
   > Failed to parse XML resource file 'C:\Users\XXX\AppData\Local\Temp\f8580962-92de-4c7e-a6ea-67211aa38ed2\androidx.appcompat\build\intermediates\packaged_res\release\values\values.xml'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

        at com.adobe.air.apk.AABOutputStream.buildGradle(AABOutputStream.java)
        at com.adobe.air.apk.AABPackager.renameOutput(AABPackager.java)
        at com.adobe.air.ApplicationPackager.createPackage(ApplicationPackager.java)
        at com.adobe.air.apk.AABPackager.createPackage(AABPackager.java)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java)
        at com.adobe.air.ADT.run(ADT.java)
        at com.adobe.air.ADT.main(ADT.java)
`

Device logs if relevant

**Comment by lwmirkk** [comment]
Solved:
Updated Gradle from 31 to 32
Installed /Enabled Android 30

Instructions from:
https://airsdk.dev/docs/tutorials/platform/android/packaging-android-app-bundles

**Comment by marchbold** [comment]
Glad you found your issue.
