### ISSUE TITLE
Compile error when using androidx.core-1.6.0 (1.3.2 works)

### ISSUE THREAD

**Issue by lwmirkk** [distriqt/ANE-AndroidSupport#18]
##### Expected behaviour
Compile APK

##### Actual behaviour
Compiler error and stop.

##### Environment 

- AIR SDK version: 33.1.1.795
- Device OS: Target Android - APK - Gradle
- Development IDE: Animate to SWF + CMD 
- Development OS: Windows 10 x64

##### Logs

```
> 
> NOTE: Multiple Android build-tools folders exist, choosing the latest version (32.0.0) for packaging
> aapt tool failed:C:\Users\***\AppData\Local\Temp\56dcdce1-6434-4a8b-87aa-9f13f06db506\savedstate-1.1.0-res\values\values.xml:3: error: Found tag id where item is expected
> 
> C:\Users\***\AppData\Local\Temp\56dcdce1-6434-4a8b-87aa-9f13f06db506\lifecycle-viewmodel-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected
> 
> C:\Users\***\AppData\Local\Temp\56dcdce1-6434-4a8b-87aa-9f13f06db506\lifecycle-runtime-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected
> 
```

Extensions:
> <extensionID>androidx.appcompat (1.4.1)</extensionID>
>     <extensionID>androidx.core (1.3.2)</extensionID>
>     <extensionID>androidx.vectordrawable (1.1.0)</extensionID>
>     <extensionID>com.distriqt.Application (6.8.4)</extensionID>
>     <extensionID>com.distriqt.Core (6.4.3)</extensionID>
>     <extensionID>com.distriqt.Exceptions (3.0.8)</extensionID>
>     <extensionID>com.distriqt.MediaPlayer (4.6.0)</extensionID>
>     <extensionID>com.distriqt.PackageManager (3.2.2)</extensionID>
>     <extensionID>com.distriqt.RestartApp (3.0.14)</extensionID>
>     <extensionID>com.google.code.gson.gson (2.8.6)</extensionID>
>     <extensionID>com.google.guava (31.0.1)</extensionID>
>     <extensionID>com.mesmotronic.ane.fullscreen (1.5.0)</extensionID>
>     <extensionID>com.tuarua.frekotlin (1.42.0)</extensionID>
>     <extensionID>com.tuarua.WebViewANE (2.24.0)</extensionID>

**Comment by marchbold** [comment]
Please update your build tools in Android Studio. We require version 33 now to support the latest Android features.

**Comment by lwmirkk** [comment]
I tried with 33.0.0 rc1 and returned same error:
```
NOTE: Multiple Android build-tools folders exist, choosing the latest version (33.0.0 rc1) for packaging
aapt tool failed:C:\Users\***\AppData\Local\Temp\c05a7a6e-7e5c-4e67-b98d-bb9e9d36deba\savedstate-1.1.0-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\***\AppData\Local\Temp\c05a7a6e-7e5c-4e67-b98d-bb9e9d36deba\lifecycle-viewmodel-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\***\AppData\Local\Temp\c05a7a6e-7e5c-4e67-b98d-bb9e9d36deba\lifecycle-runtime-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected
```

**Comment by marchbold** [comment]
Java 11 is correct.

Are you using the legacy build mode?

**Comment by marchbold** [comment]
@httpwebmedia Please try updating your build tools, I believe 33 is the latest not 30.

**Comment by marchbold** [comment]
I'll be continuing this here: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1762
