### ISSUE TITLE
Error creating files: aapt tool

### ISSUE THREAD

**Issue by marcanw** [distriqt/ANE-AndroidSupport#19]
![image](https://user-images.githubusercontent.com/21979056/157777545-e6532cb3-3698-435b-99e3-6d1b2c925bc3.png)

- AIR SDK version: 33.1.1.795
- Development IDE: Animate
- Development OS: Windows

**Comment by marchbold** [comment]
Please see this discussion

https://github.com/airsdk/Adobe-Runtime-Support/discussions/1762
