### ISSUE TITLE
Latest androidx.core throwing build errors in value.xml

### ISSUE THREAD

**Issue by Formability** [distriqt/ANE-AndroidSupport#20]
I'm using the CameraUI ane.

I updated to the latest version of androidx.core (commit de779cc72e4a57212891e3cc1544bb4b18f33cf5) and my builds fail with the following error

```
aapt tool failed:C:\Users\John\AppData\Local\Temp\7d072876-9c72-4c4e-96a3-1b4edabf7f8d\savedstate-1.1.0-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\John\AppData\Local\Temp\7d072876-9c72-4c4e-96a3-1b4edabf7f8d\lifecycle-viewmodel-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected

C:\Users\John\AppData\Local\Temp\7d072876-9c72-4c4e-96a3-1b4edabf7f8d\lifecycle-runtime-2.3.1-res\values\values.xml:3: error: Found tag id where item is expected
```

If I use the version from commit 11907165ef5efb374aa13a3f4d7157836060bef3 it all works OK again.

**Comment by marchbold** [comment]
Please see: https://github.com/airsdk/Adobe-Runtime-Support/discussions/1762

You need to use the new build process and apparently there was an issue in the latest AIR SDK that defaults to the legacy method.
