### ISSUE TITLE
Error: 'io.reactivex' required by the application was not found for the target platform.

### ISSUE THREAD

**Issue by megajogos** [distriqt/ANE-AndroidSupport#24]
We have configured our project with APM but when we try to build the Android APK we got the following error:

```An implementation for native extension 'io.reactivex' required by the application was not found for the target platform.```

**Comment by marchbold** [comment]
Can you provide some context to this error, what extensions are you using in your application? If you post the project.apm that could be helpful.

apm won't remove extensions from your extension list if you are updating an existing  application descirptor.  So if you previously had this extension in there and it is not required by any of the packages you are using you may have to manually remove it.

**Comment by shaymolho** [comment]
this happens to me:
`An implementation for native extension 'com.bumptech.glide' required by the application was not found for the target platform.`

**Comment by marchbold** [comment]
@shaymolho I'd suggest you check you've run the install and are pointing your build process to the ane folder created by apm. I've just done a check on your project file and it correctly downloads the glide ane.

**Comment by shaymolho** [comment]
yes that was the problem, thanks

**Comment by shaymolho** [comment]
Now I'm getting this:

**Comment by marchbold** [comment]
Looks like you have a lot of duplicate classes in there, are you including multiple versions of the ane's in your build? Or ANEs from another provider - not via apm?

**Comment by shaymolho** [comment]
I'm also including appsflyer ANE https://github.com/AppsFlyerSDK/AdobeAirExtension-AppsFlyer manually (not via APM)

**Comment by shaymolho** [comment]
but also after removing it i still see a lot of duplicates errors in the log

**Comment by marchbold** [comment]
Not sure what the "strict" version is but we normally use the `AppsFlyerAIRExtension-witout-gp-support.ane`. The "without gp support" ANE doesn't have the Google Play Services and AndroidX/AndroidSupport libs included. Their main ANE includes these libraries and causes the conflicts.
