### ISSUE TITLE
Error when apk/ipa Build & SWF Launch on VScode

### ISSUE THREAD

**Issue by everseen83** [distriqt/ANE-AndroidSupport#28]
### Case 1. When launch SWF, the following error occurs.

>Error launching SWF debug session. Process exited with code: 5 
Error: The extension androidx.browser has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.

### Case 2. When building the "apk/ipa" file, the following error occurs.
> Included native extension 'androidx.constraintlayout' includes a SWF version 44 which is greater than the version of the root SWF of this application: 43
> The terminal process "/Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/java '-jar', '/Users/everseen/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.12.1/bin/asconfigc.jar', '--sdk', '/Users/_Libraries/AIR33.1.1.889', '--debug=false', '--project', '/Users/Projects/Starling/TheCat/asconfig.json', '--air', 'android'" terminated with exit code: 12.
> 

##### Environment 

- AIR SDK version: 33.1.1.889
- Development IDE: VS code
- Development OS: OSX

##### Dependencies 
```
{
    "version": "6.11.0",
    "id": "com.distriqt.admob.FacebookAudience"
},
{
    "version": "6.1.3",
    "id": "com.distriqt.ApplicationRater"
},
{
    "version": "8.6.11",
    "id": "com.distriqt.Dialog"
},
{
    "version": "6.9.2",
    "id": "com.distriqt.Application"
},
{
    "version": "4.2.1",
    "id": "com.distriqt.admob.UnityAds"
},
{
    "version": "5.1.0",
    "id": "com.distriqt.IDFA"
},
{
    "version": "6.3.1",
    "id": "com.distriqt.Notifications"
},
{
    "version": "7.1.2",
    "id": "com.distriqt.Share"
},
{
    "version": "13.2.1",
    "id": "com.distriqt.InAppBilling"
},
{
    "version": "8.0.3",
    "id": "com.distriqt.GameServices"
},
{
    "version": "7.0.1",
    "id": "com.distriqt.Firebase"
}
```

**Comment by marchbold** [comment]
Are you setting a swf version in your package command?

**Comment by everseen83** [comment]
In VS code -asconfig.json , the "swf version" does not exist in the default state, so adding it solved the problem.

```
"compilerOptions": {
    "swf-version": 44,
....

```
Thanks for your help.
