### ISSUE TITLE
Build/Run/Debug Error

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-AndroidSupport#30]
I can't build/run/debug the app with Intellij Idea.

I have error:

aapt tool failed:
C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\savedstate-1.2.1-res\values\values.xml:3: error: Found tag id where item is expected C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\lifecycle-viewmodel-2.6.1-res\values\values.xml:3: error: Found tag id where item is expected C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\lifecycle-runtime-2.6.1-res\values\values.xml:3: error: Found tag id where item is expected C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\activity-1.7.0-res\values\values.xml:4: error: Found tag id where item is expected C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\constraintlayout-2.1.4-res\values\values.xml:1491: error: Attribute "android:translationX" has already been defined C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\constraintlayout-2.1.4-res\values\values.xml:1495: error: Attribute "android:translationY" has already been defined C:\Users\Dmytro\AppData\Local\Temp\64d912a9-3ad9-4f2e-9824-067c4a56a6a3\constraintlayout-2.1.4-res\values\values.xml:1498: error: Attribute "android:translationZ" has already been defined

Earlier I could build/run with  older version of AIR SDK for debugging (I usually used 3.1.1.795. I Couldn't build/run/debug with newer AIR SDK than 33.1.1.795 )
Now I can't do this because of com.google.code.gson ANE

But I can build aab with latest AIR SDK from command promt.

Can you help me to solve this?

**Comment by marchbold** [comment]
This likely indicates you are using the legacy build method. Have you installed android studio (or the android sdk) and set the path in your adt.cfg or through the AIR SDK Manager?
