### ISSUE TITLE
com.google.code.gson.ane  and namespace 50.2

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-AndroidSupport#33]
I use AIR 33.1.935 and notice that only this extension need AIR 50.2.

Can I update other ANEs and use old version for com.google.code.gson.ane?
I need this ANE because of using IronSource ANE.

I  have plans to update to AIR 50.2 but don't know what is the stable version?
AIR 33.1.935 is stable for production for me so I don't want to check my luck)

**Comment by marchbold** [comment]
Hi, If you want to keep using AIR 33, you'll need to use the old versions of our extensions. We are migrating to the new gradle dependencies in AIR 50.2 which makes some of the newer libraries accessible more easily to us.

**Comment by Mintonist** [comment]
Does it mean that all of your ANEs will be using 50.2 in nearest future?

**Comment by marchbold** [comment]
Not in the near future but we will be migrating over time. The new systems increase stability and reduce the maintenance in updating extensions so we should be able to provide more frequent updates.

**Comment by Mintonist** [comment]
Can you recommend a stable version of AIR 50?

**Comment by marchbold** [comment]
I would suggest using the latest, but it can depend on which features of the SDK you are using.
