### ISSUE TITLE
help installing androidx.core extension

### ISSUE THREAD

**Issue by RacheliGolan** [distriqt/ANE-AndroidSupport#7]
I have an app which I am trying to upgrade to 64 bit.
I am replacing this extenstion:
<extensionID>com.distriqt.androidsupport.V4</extensionID>
 with the following:
<extensionID>androidx.core</extensionID>

I cant manage to install the androidx.core extenstion.
 when I run my app I get in the oneSignal manager this error: Missing Android Support Library.

any Idea why?

![temp](https://user-images.githubusercontent.com/22295597/91042396-594d5580-e61a-11ea-839e-913e35a14b73.png)

**Comment by marchbold** [comment]
Unfortunately you can't use androidx and android support libs in the same project. You'll need to get a recent release of all your extensions that support android x or remove the ones that depend on the old android support libs.

**Comment by RacheliGolan** [comment]
Is'nt that what I did?
I switched extentions to a more updated one.

I followed the instructions here:
https://github.com/marpies/onesignal-ane/releases

**Comment by marchbold** [comment]
I don't see any mention of updating to androidx there? Onesignal needs to be converted to support androidx. We have done this with our push notifications ANE.

**Comment by RacheliGolan** [comment]
thank you!
