### ISSUE TITLE
ANE dependencies

### ISSUE THREAD

**Issue by Mintonist** [distriqt/ANE-AndroidSupport#8]
I make code revision of game before store launch.

For along time I can not find info about this ANEs which I have integrated early)) 

<extensionID>com.google.android.datatransport</extensionID>
<extensionID>com.google.dagger</extensionID>

It will be very helpfully if you describe what of your Extensions can use different AndroidSupport libraries. Seems https://github.com/distriqt/ANE-AndroidSupport/wiki has outdated information. For example only ANE-PushNotifications required:
androidx.core
androidx.appcompat
androidx.browser
androidx.cardview
androidx.constraintlayout
androidx.vectordrawable
com.google.android.datatransport
com.google.dagger
com.google.protobuflite

Thx!

**Comment by marchbold** [comment]
This information is included with the individual ANEs independently of this repository. 

We only included some examples here as this should not be the place to retrieve this information.
